### ISSUE TITLE
Need to exclude builtin Firefox themes

### ISSUE THREAD

**Issue by realstephenzhao** [drsjb80/personaswitcher#35]
Please add an option to exclude the builtin Firefox themes(3?) when automatically switching between these themes.

Thanks

**Comment by JasonGould81** [comment]
This has been a common request; so much so that both the latest version of Persona Switcher as well as the previous bootstrap version both skip the built-in Firefox themes when automatically switching between themes (if non-default themes are installed). If you are experiencing different behavior, i.e. the default themes showing up in the auto-rotation lineup, would you mind replying with the version of Persona Switcher you are using, the version of FF,  your OS, and when this issue seems to manifest so that we can troubleshoot the issue?
Thanks!

**Comment by realstephenzhao** [comment]
I just test it many times before replying to you.

The feature that would supposed to skip the built-in Firefox themes which you mentioned above doesn't work for me.

Environment:
Persona Switcher 5.0.2, Firefox Quantum 57 on Windows 10 Home 1703, Simplified Chinese

P.S. The Chinese Translation(Localization) of Persona Switcher seems weird, confused and inaccurate, how can I check the original menu text(Maybe Written in English)?

**Comment by JasonGould81** [comment]
> Does Persona Switcher use an way by matching English words of themes to identify if it is a built-in theme? 

Good catch, that is exactly what was happening. The identification of default themes has now been switched to what is *hopefully* a locale independent attribute. I have pushed up a fix and am just waiting for confirmation from the Persona Switcher author that the fix is solving the issue for him as well. If so, he should be able to let you know when the update will be published to Mozilla for download. Thanks for all your effort in helping track down the issue, it's much appreciated!

**Comment by realstephenzhao** [comment]
And you're doing a great job, many thanks to you. @JasonGould81

**Comment by drsjb80** [comment]
Pulled, committed, pushed, uploaded to Mozilla, now available there. Code looks great! No errors or warnings from Mozilla either. Thanks to both of you!

**Comment by drsjb80** [comment]
I'll send the source out today to our translators so they can fix things up. I've been waiting for 57 to hit the streets so they can test with it.

**Comment by realstephenzhao** [comment]
Problem solved, thank you.
